### ISSUE TITLE
Create the pipeline to build and push the custom check image

### ISSUE THREAD

**Issue by edsoncelio** [edsoncelio/kuberhealthy-grafana-demo#2]
```yaml
name: ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./custom-check-demo/
          push: true
          tags: user/app:latest
```
